### PR TITLE
Develop refactor bugfixes 2

### PR DESCRIPTION
**Pull request by Czahrien**
Fixes for a couple of issues and an enhancement request.

You will want to look over the survey changes to make sure it is what you were expecting. 

The group guarding changes seemed pretty straightforward to me but double check that I did not overlook anything with the group applications - I matched the logic up in the dashboard routine in the groups view when determining who can apply to what groups.

### CODE REVIEW

**Comment by porowns** [comment]
Group guards need to check for PUBLIC as well, since a guild group can be public but they can still input the URL

**Comment by porowns** [comment]
For the user check for guilds, just do `if guild in user.guilds_in.all()` instead of going through all guilds and guild groups (which could sort of get out of hand performance wise)

**Comment by Czahrien** [comment]
It should be better now

**Comment by porowns** [comment]
Looks good to me as long as the tests went well :D

**Pull request merged**
